### ISSUE TITLE
gb-test-roms/cpu_instrs を通す

### ISSUE THREAD

**Issue by kigh-ota** [sacchie/gbem#11]
- [x] 01-special.s
- [x] 02-interrupts.s
- [x] 03-op sp,hl.s
- [x] 04-op r,imm.s
- [x] 05-op rp.s
- [x] 06-ld r,r.s
- [x] 07-jr,jp,call,ret,rst.s
- [x] 08-misc instrs.s
- [x] 09-op r,r.s
- [x] 10-bit ops.s
- [x] 11-op a,(hl).s

**Comment by kigh-ota** [comment]
<img width="912" alt="スクリーンショット 2023-11-14 19 40 04" src="https://github.com/sacchie/gbem/assets/459628/a902a7be-e159-41d7-880a-8b8811f22fbf">

**Comment by kigh-ota** [comment]
<img width="912" alt="スクリーンショット 2023-11-14 19 41 04" src="https://github.com/sacchie/gbem/assets/459628/2b87c3ca-2f11-4f11-8830-2289f338e69c">

**Comment by kigh-ota** [comment]
<img width="592" alt="スクリーンショット 2023-11-14 19 42 12" src="https://github.com/sacchie/gbem/assets/459628/40e85aa2-5e83-4d6d-97d2-152cca4c75e8">

**Comment by kigh-ota** [comment]
<img width="592" alt="スクリーンショット 2023-11-14 19 43 04" src="https://github.com/sacchie/gbem/assets/459628/74f1b526-a975-4d71-a945-596cd91b8469">

**Comment by kigh-ota** [comment]
07は例外でダメ

```
*** 0xc679: OpJpN16(n=0xDEF8)
Exception in thread "main" java.lang.RuntimeException: Invalid opcode: d9, addr: def8
	at cpu.ParseKt.parse(parse.kt:336)
	at MainKt.loop(main.kt:28)
	at MainKt.main(main.kt:65)
```

**Comment by kigh-ota** [comment]
08
```
**** 0xdef8: OpLdD16SP(d=0xFF91)
Exception in thread "main" java.lang.RuntimeException: Invalid address: 0xff91
	at MemoryImpl.set16(main.kt:287)
	at cpu.RunKt.run(run.kt:324)
	at MainKt.loop(main.kt:31)
	at MainKt.main(main.kt:65)
```

**Comment by kigh-ota** [comment]
<img width="592" alt="スクリーンショット 2023-11-14 19 46 51" src="https://github.com/sacchie/gbem/assets/459628/3820d08a-8c0e-4064-b882-5e3307a0a457">
<img width="592" alt="スクリーンショット 2023-11-14 19 47 49" src="https://github.com/sacchie/gbem/assets/459628/5b2d5260-87ad-4bed-b228-f72d80e29259">
<img width="592" alt="スクリーンショット 2023-11-14 19 49 02" src="https://github.com/sacchie/gbem/assets/459628/fc09e2da-0b67-4ece-abec-d5ba82b46239">

**Comment by kigh-ota** [comment]
<img width="592" alt="スクリーンショット 2023-11-14 19 50 15" src="https://github.com/sacchie/gbem/assets/459628/34758093-3d05-4ff2-8280-31312ddf035a">

**Comment by kigh-ota** [comment]
<img width="592" alt="スクリーンショット 2023-11-14 19 54 23" src="https://github.com/sacchie/gbem/assets/459628/82e3cba3-3d40-4b90-90db-6e00f0bcfab5">

**Comment by kigh-ota** [comment]
<img width="592" alt="スクリーンショット 2023-11-14 21 17 34" src="https://github.com/sacchie/gbem/assets/459628/306485ef-ad6d-4824-824f-5ec6286c6634">

**Comment by kigh-ota** [comment]
11/14
次回
- 02のテスト（割り込み）を通す
- その後、https://elekibear.com/20210612_01 でも実行できるようにする
  - 0xFF46 (DMA) が動いてないのでそこから

**Comment by hmaeta** [comment]
```
*** 0xc17c: OpPopR16(r=AF)
*** 0xc17d: OpRet()
** 0xc2ae: OpJrD8(d=0x4)
** 0xc2b4: OpPopR16(r=HL)
** 0xc2b5: OpEi()
** 0xc2b6: OpLdR16D16(r=BC, d=0x0)
** 0xc2b9: OpPushR16(r=BC)
set16: [0xdffb] <- 0x0
** 0xc2ba: OpPopR16(r=BC)
** 0xc2bb: OpIncR8(r=B)
** 0xc2bc: OpLdR8D8(r=A, d=0x4)
** 0xc2be: OpLdToIoPort(d=0xF)
** 0xc2c0: OpDecR8(r=B)
** 0xc2c1: OpJpFNn(f=NZ, n=0xC1B9)
** 0xc2c4: OpLdHLSpAndD8(d=0xFE)
** 0xc2c6: OpLdiAHL()
** 0xc2c7: OpCpAD8(d=0xC0)
** 0xc2c9: OpJpFNn(f=NZ, n=0xC1B9)
** 0xc1b9: OpLdAD16(d=0xD805)
** 0xc1bc: OpLdR8R8(x=L, y=A)
```

**Comment by hmaeta** [comment]
次回:
- テストを通すにはサイクルの概念を導入し、IFレジスタのTIMERビットを立てる必要がある。
- 各OPコード毎にサイクル数が対応するがこの変更は大変そうなのでとりあえず平均サイクル数 (2とか4) で代用できないか試してみる。

**Comment by kigh-ota** [comment]
11/28メモ

- GBでは 1 cycle = 4 CPU clocks
- 各Op実行ごとに 4 cycle とかかかる
- Timerはcycle/clockをカウントしている

**Comment by kigh-ota** [comment]
12/5 メモ

- cycleを雑に 8 cycle / op でカウントして、timer を最低限部分実装した
  - set_test 4 は pass
- set_test 5 内の halt が未実装で落ちる → 次は halt の実装から

**Comment by hmaeta** [comment]
![image](https://github.com/sacchie/gbem/assets/12731394/5d25968d-c720-4202-aa53-cd27bb33b973)

**Comment by hmaeta** [comment]
2024/01/16

このissueが終わった。
次にやることは未定。
次にやること案:
- ほかのテストを通す
- フリーのロムで動かしてみる
- 修正コミットから、どういうバグを入れ込んでいたの分析、役に立ったプラクティスを言語化、などの振り返り。

**Comment by kigh-ota** [comment]
> 修正コミットから、どういうバグを入れ込んでいたの分析、役に立ったプラクティスを言語化、などの振り返り。

https://github.com/sacchie/gbem/pull/12

- Op
  - RSTのミス（CALLで実装してたが、仕様が違った。RSTは特定のアドレスにのみ飛べる分命令長が2バイト短い）
- パーサー
  - opcode D9 (RETI) の対応漏れ

https://github.com/sacchie/gbem/pull/8

- パーサー
  - opcode 09,19,29,39 の対応漏れ
  - opcode 0A,1A,2A,3A の対応漏れ
  - opcode 0B,1B,2B,3B の対応漏れ
  - opcode CD (CALL) を誤って CC でパースしてた
  - opcode C9 (RET) の対応漏れ
- Op
  - JR のジャンプ先アドレス計算に命令長を足してなかった
  - POP R16 で AF対象の場合に下4bitをつぶし忘れていた
  - 条件付きジャンプのC条件の実装ミス
  - DAAの実装ミス（下ろすフラグを間違えてた）

### プラクティス

- デバッガーの表示内容を16進数に変えて見やすい
- コールスタックの段数をコンソールに表示
- タイマーに加算するサイクル数を、命令長を考慮せず暫定で定数にしてとりあえず通った
- テストROMのコードを参照して落ちた原因を分析
- CPUとPPUを依存無しで開発し、結合がスムーズにできた
  - PPUの単体テストを通しながら開発しinterfaceを維持
