### ISSUE TITLE
molemoleを動かす

### ISSUE THREAD

**Issue by kigh-ota** [sacchie/gbem#17]
https://github.com/dotnsf/gbdk/tree/main/4.molemole を動かしてみる
→ FF46 — DMA: OAM DMA source address & start が未実装でエラー
https://gbdev.io/pandocs/OAM_DMA_Transfer.html?highlight=FF46#ff46--dma-oam-dma-source-address--start

https://dotnsf.blog.jp/archives/1082148497.html

- [x] FF46 OAM DMAの実装 2024-01-23
- [x] LYを更新しながらscanlineごとに描画 2024-01-23
- [x] Joypadの入力の実装

**Comment by hmaeta** [comment]
2024/01/30
ボタンを押して下方向に動かすことは成功。
ただし動作は遅い。
